---
- name: Create Gitea directory
  ansible.builtin.file:
    path: /opt/gitea
    state: directory
    mode: "0755"

- name: Render Gitea docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/gitea/docker-compose.yml
    mode: "0644"

- name: Start Gitea stack
  community.docker.docker_compose_v2:
    project_src: /opt/gitea
    state: present
