---
- name: Create Traefik directory
  ansible.builtin.file:
    path: /opt/traefik
    state: directory
    mode: "0755"

- name: Create acme.json if it doesn't exist
  ansible.builtin.copy:
    dest: /opt/traefik/acme.json
    content: ""
    mode: "0600"
    force: false  # <-- C'est la clé magique ! Ansible ne le créera que s'il n'existe pas.

- name: Render Traefik static config
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: /opt/traefik/traefik.yml
    mode: "0644"

- name: Render Traefik docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/traefik/docker-compose.yml
    mode: "0644"

- name: Start Traefik stack
  community.docker.docker_compose_v2:
    project_src: /opt/traefik
    state: present
