---
# ==========================================
# 1. CONFIGURATION COMMUNE (Network, Media, Apps)
# ==========================================
- name: Setup Base OS & Docker
  hosts: debian_vms
  become: true
  tags: base
  vars_files:
    - vault/secrets.yml
  roles:
    - role: docker

# ==========================================
# 2. NET & PROXY (192.168.1.11)
# ==========================================
- name: Deploy Network & Proxy Services
  hosts: network
  become: true
  tags: network
  vars_files:
    - vault/secrets.yml
  roles:
    - role: traefik
    - role: pihole      # <--- Hop, plus aucune tâche indépendante !

# ==========================================
# 3. MEDIA & FICHIERS (192.168.1.12)
# ==========================================
- name: Deploy Media Services
  hosts: media
  become: true
  tags: media
  vars_files:
    - vault/secrets.yml
  roles:
    - role: immich
    - role: jellyfin
    - role: navidrome
    - role: gokapi

# ==========================================
# 4. APPS, DEV & GAMING (192.168.1.13)
# ==========================================
- name: Deploy Apps, Dev & Gaming Services
  hosts: apps
  become: true
  tags: apps
  vars_files:
    - vault/secrets.yml
  roles:
    - role: gitea
    - role: searxng
    - role: uptimekuma
    - role: radicale
    - role: joplin
    - role: shlink
    - role: speedtest
    - role: crafty