- name: Setup Jellyfin server
  hosts: jellyfin
  become: true

  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Create Jellyfin folder
      file:
        path: /opt/jellyfin
        state: directory

    - name: Copy docker-compose
      copy:
        src: ../docker/jellyfin/compose.yml
        dest: /opt/jellyfin/compose.yml

    - name: Run Jellyfin
      shell: docker compose up -d
      args:
        chdir: /opt/jellyfin